package visao;

/**
 *
 * @author laisp
 */
public class Menu_prin extends javax.swing.JFrame {

    /**
     * Creates new form Menu_prin
     */
    public Menu_prin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadPessoa = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmCadAgenda = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jmcadexame = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jmtabpessoa = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jmtabagenda = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jmtabexame = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.jpg"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jmCadPessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastro.png"))); // NOI18N
        jmCadPessoa.setText("Novo Cadastro");

        jMenuItem2.setText("Cadastro");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmCadPessoa.add(jMenuItem2);

        jMenuBar1.add(jmCadPessoa);

        jmCadAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/agenda.png"))); // NOI18N
        jmCadAgenda.setText("Novo Agenda");

        jMenuItem3.setText("Agenda");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jmCadAgenda.add(jMenuItem3);

        jMenuBar1.add(jmCadAgenda);

        jmcadexame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exame.png"))); // NOI18N
        jmcadexame.setText("Novo Exame");

        jMenuItem4.setText("Exame");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jmcadexame.add(jMenuItem4);

        jMenuBar1.add(jmcadexame);

        jmtabpessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastro tabela.png"))); // NOI18N
        jmtabpessoa.setText("Consulta Cadastro");

        jMenuItem5.setText("Consulta Cadastro ");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jmtabpessoa.add(jMenuItem5);

        jMenuBar1.add(jmtabpessoa);

        jmtabagenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/agenda tabela.png"))); // NOI18N
        jmtabagenda.setText("Consulta Agenda");

        jMenuItem6.setText("Consulta Agenda");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jmtabagenda.add(jMenuItem6);

        jMenuBar1.add(jmtabagenda);

        jmtabexame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exame tabela.png"))); // NOI18N
        jmtabexame.setText("Consulta Exame");

        jMenuItem7.setText("Consulta Exame");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jmtabexame.add(jMenuItem7);

        jMenuBar1.add(jmtabexame);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 972, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        abrirTabExame();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        abrirTabAgenda();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        abrirTabPessoa();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        abrirCadExame();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        abrirCadAgenda();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        abrirCadPessoa();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void abrirCadPessoa(){
        Tela_cad_pessoa tcp = new Tela_cad_pessoa();
        tcp.setVisible(true);
    }//fecha método
    
    private void abrirCadAgenda(){
        Tela_cad_agenda tca = new Tela_cad_agenda();
        tca.setVisible(true);
    }
    
    private void abrirCadExame(){
        Tela_cad_exame tca = new Tela_cad_exame();
        tca.setVisible(true);
    }
    
    private void abrirTabPessoa(){
        Tela_tab_pessoa ttp = new Tela_tab_pessoa();
        ttp.setVisible(true);
    }
    
    private void abrirTabAgenda(){
        Tela_tab_agenda tta = new Tela_tab_agenda();
        tta.setVisible(true);
    }
    
    private void abrirTabExame(){
        Tela_tab_exame tte = new Tela_tab_exame();
        tte.setVisible(true);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_prin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_prin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_prin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_prin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_prin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenu jmCadAgenda;
    private javax.swing.JMenu jmCadPessoa;
    private javax.swing.JMenu jmcadexame;
    private javax.swing.JMenu jmtabagenda;
    private javax.swing.JMenu jmtabexame;
    private javax.swing.JMenu jmtabpessoa;
    // End of variables declaration//GEN-END:variables
}
